---
- name: Install Logstash
  ansible.builtin.apt:
    name: logstash
    state: present
  notify: Restart Logstash

- name: Configure Logstash pipeline
  ansible.builtin.template:
    src: 02-beats-input.conf.j2
    dest: /etc/logstash/conf.d/02-beats-input.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Logstash

- name: Ensure Logstash service is started and enabled
  ansible.builtin.systemd:
    name: logstash
    state: started
    enabled: yes
