---
- name: Install single-node k3s (server)
  hosts: k3s_master
  become: true
  vars:
    k3s_version: v1.30.1+k3s1
  tasks:
    - name: 下載官方安裝腳本
      get_url:
        url: "https://get.k3s.io"
        dest: /tmp/install_k3s.sh
        mode: '0755'

    - name: 安裝k3s
      command: "INSTALL_K3S_VERSION={{ k3s_version }} /tmp/install_k3s.sh"
      args:
        creates: /usr/local/bin/k3s

    - name: 複製kubeconfig供之後Helm/k8s模組使用
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/{{ ansible_user }}/.kube/config
        remote_src: yes
        owner: "{{ ansible_user }}"
        mode: '0600'
