---
- name: Install Kibana
  ansible.builtin.apt:
    name: kibana
    state: present
  notify: Restart Kibana

- name: Configure Kibana
  ansible.builtin.template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: kibana
    mode: '0660'
  notify: Restart Kibana

- name: Ensure Kibana service is started and enabled
  ansible.builtin.systemd:
    name: kibana
    state: started
    enabled: yes

- name: Allow Kibana port through firewall
  community.general.ufw:
    rule: allow
    port: '5601'
    proto: tcp

