---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install prerequisite packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - gnupg2
      - openjdk-17-jdk
    state: present
