---
- name: Add Elastic GPG key
  ansible.builtin.get_url:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    dest: /etc/apt/trusted.gpg.d/elastic-8.x.asc
    mode: '0644'
    force: true

- name: Add Elastic repository
  ansible.builtin.apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
    state: present
    filename: elastic-8.x

- name: Install Elasticsearch
  ansible.builtin.apt:
    name: elasticsearch
    state: present
    update_cache: yes
  notify: Restart Elasticsearch

- name: Configure Elasticsearch
  ansible.builtin.template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: '0660'
  notify: Restart Elasticsearch

- name: Ensure Elasticsearch directories have correct permissions
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
    recurse: yes
  loop:
    - /etc/elasticsearch
    - /var/lib/elasticsearch
    - /var/log/elasticsearch

- name: Allow Elasticsearch internal communication port through firewall
  community.general.ufw:
    rule: allow
    port: '9300'
    proto: tcp

- name: Allow Elasticsearch HTTP port through firewall
  community.general.ufw:
    rule: allow
    port: '9200'
    proto: tcp

- name: Ensure Elasticsearch service is started and enabled
  ansible.builtin.systemd:
    name: elasticsearch
    state: started
    enabled: yes
